In [1]:
import pandas as pd
import numpy as np

In [2]:
fin=pd.read_csv('finalml.csv')

In [15]:
fin

Name  Speciality  Degree  Year_of_experience  \
0           Dr. Sumanth Shetty           1      56                  24   
1             Dr. Jnanesha H.C           1      47                  21   
2         Dr. J Samuel Santosh           1      30                  17   
3               Dr. M J Murali           1     817                  26   
4            Dr. Ganesh Shetty           1      72                  25   
...                        ...         ...     ...                 ...   
5150         Dr. Haresh Asnani           8     689                  37   
5151          Dr. Nidhi Thaker           8     366                  13   
5152          Dr. Sunita Meena           8     689                  14   
5153  Dr. Prashant M Koranmath           8     888                   9   
5154           Dr. Mitesh Jain           8     366                  19   

      Location  City  dp_score   npv  consultation_fee  
0          202     0        97  4311               300  
1          161     0        98   260               300  
2          419     0        94    71               300  
3          139     0        99   148               300  
4          180     0        98  3788               500  
...        ...   ...       ...   ...               ...  
5150        55     2       100    17               800  
5151       109     2       100    17               700  
5152        54     2       100    17              1000  
5153       241     2       100    17              1200  
5154        55     2       100    17               800  

[5155 rows x 9 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
# LabelEncoding
le=LabelEncoder()

In [6]:
le.fit(fin['Location'])

LabelEncoder()

In [7]:
location_dict = dict(zip(le.classes_, le.transform(le.classes_)))

In [33]:
location_dict

{'AECS Layout': 0,
 'Adarsh Nagar': 1,
 'Akshaya nagar': 2,
 'Alaknanda': 3,
 'Anand Vihar': 4,
 'Andheri': 5,
 'Andheri East': 6,
 'Andheri West': 7,
 'Ansari Nagar': 8,
 'Arekere': 9,
 'Ashok Vihar': 10,
 'Ashok Vihar Phase 1': 11,
 'Ashok Vihar Phase 3': 12,
 'Ashoknagar': 13,
 'B Narayanapura': 14,
 'BTM Layout': 15,
 'BTM Layout 1st Stage': 16,
 'BTM Layout 2nd Stage': 17,
 'Bagalakunte': 18,
 'Bagalur': 19,
 'Bali Nagar': 20,
 'Banashankari': 21,
 'Banashankari 1st Stage': 22,
 'Banashankari 2nd Stage': 23,
 'Banashankari 3rd Stage': 24,
 'Banaswadi': 25,
 'Bandra': 26,
 'Bandra East': 27,
 'Bandra West': 28,
 'Bannerghatta Road': 29,
 'Basavanagudi': 30,
 'Basaveshwaranagar': 31,
 'Begur': 32,
 'Belathur': 33,
 'Bellandur': 34,
 'Bhandup': 35,
 'Bhandup West': 36,
 'Bhogal': 37,
 'Bilekahalli': 38,
 'Bommanahalli': 39,
 'Bommasandra': 40,
 'Borivali': 41,
 'Borivali East': 42,
 'Borivali West': 43,
 'Brigade Road': 44,
 'Brookefield': 45,
 'Burari': 46,
 'CR Park': 47,
 'CV Rama

In [8]:
le.fit(fin['Degree'])

LabelEncoder()

In [9]:
degree_dict = dict(zip(le.classes_, le.transform(le.classes_)))

In [32]:
degree_dict

{' FRCP, DM - Neurology, MBBS': 0,
 ' FRCP, MBBS, Member of the Royal College of Paediatrics and Child Health (MRCPCH, London, Glasgow or Edinburgh), MRCP (UK)': 1,
 'B.Sc. - Home Science (Food & Nutrition)': 2,
 'B.Sc. - Home Science (Food & Nutrition), M.Sc. - Home Science (Food & Nutrition)': 3,
 'B.Sc.- Clinical Nutrition & Dietetics, M.Sc. - Home Science (Food & Nutrition), PhD - Yoga': 4,
 'BAMS': 5,
 'BAMS, DNHE': 6,
 'BAMS, Diploma in Clinical Nutrition': 7,
 'BAMS, Fellowship in Applied Nutrition(FAN)': 8,
 'BDS': 9,
 'BDS, Certificate of Oral Implantology': 10,
 'BDS, Certificate of Oral Implantology, FICOI': 11,
 'BDS, Comprehensive Course in Modern Endodontics': 12,
 'BDS, Diploma in Cosmetology': 13,
 'BDS, Diploma in Health Administration': 14,
 'BDS, Diploma in Implanthology': 15,
 'BDS, Diploma in Trichology - Cosmetology': 16,
 'BDS, FDSRCS - Fellowship in Dental Surgery, FFDRCSI': 17,
 'BDS, FICOI': 18,
 'BDS, FICOI, MICOI (USA)': 19,
 'BDS, Fellowship in Aesthetic Me

In [10]:
le.fit(fin['Speciality'])

LabelEncoder()

In [11]:
Speciality_dict = dict(zip(le.classes_, le.transform(le.classes_)))
Speciality_dict

{'Cardiologist': 0,
 'Dentist': 1,
 'Dermatologist': 2,
 'Gastroenterologist': 3,
 'Gynecologist/obstetrician': 4,
 'Infertility Specialist': 5,
 'Neurologist': 6,
 'Neurosurgeon': 7,
 'Ophthalmologist': 8,
 'Orthopedist': 9,
 'Pediatrician': 10,
 'Physiotherapist': 11,
 'Psychiatrist': 12,
 'Pulmonologist': 13,
 'Rheumatologist': 14,
 'Urologist': 15,
 'bariatric surgeon': 16,
 'chiropractor': 17,
 'dietitian/nutritionist': 18}

In [12]:
le.fit(fin['City'])

LabelEncoder()

In [13]:
City_dict = dict(zip(le.classes_, le.transform(le.classes_)))
City_dict

{'Bangalore': 0, 'Delhi': 1, 'Mumbai': 2}

In [14]:
col=['Degree','Location','City','Speciality']
for j in col:
    fin[j]=le.fit_transform(fin[j])

In [16]:
X=fin.drop(['consultation_fee','Name'],axis=1)

In [17]:
Y = fin['consultation_fee']


In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3,random_state=1)

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
reg=LinearRegression()

In [23]:
reg.fit(X_train, Y_train)

LinearRegression()

In [24]:
Y_pred=reg.predict(X_test)

In [25]:
from sklearn import metrics

In [26]:
# Mean Square Error(MSE)
MSE=metrics.mean_squared_error(Y_test, Y_pred)
print('MSE =',MSE)
# Root mean square error(RSME)
RMSE=np.sqrt(MSE)
print('RMSE =',RMSE)
# Coefficient of determination or R-squared
R2=metrics.r2_score(Y_test,Y_pred)
print('R-squared =',R2)

MSE = 180097.5661841681
RMSE = 424.37903598571893
R-squared = 0.32205961550842177


In [69]:
import pickle

In [70]:
pickle.dump(reg,open("mlpro.pkl",'wb'))

In [71]:
model = pickle.load(open("mlpro.pkl",'rb'))

In [30]:
import numpy as np

data = np.array([1, 72, 25, 180, 0, 98, 3788])
data = data.reshape(1, -1)

output = model.predict(data)


C:\Users\clash\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [31]:
output

array([686.77862395])

In [65]:
encoded_speciality = Speciality_dict.get('Cardiologist')
encoded_degree = degree_dict.get('DM - Cardiology')
encoded_city = City_dict.get('Mumbai')
encoded_location = location_dict.get('Vikhroli')
year_of_experience=5
dp_score=5
npv=10

In [66]:
arr = np.array([[encoded_speciality, encoded_degree, year_of_experience, encoded_location, encoded_city, dp_score, npv]])
arr = arr.astype(int)
arr = arr.reshape(1, -1)

In [67]:
arr

array([[  0, 149,   5, 406,   2,   5,  10]])

In [68]:
model.predict(arr)

C:\Users\clash\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1224.54093316])